### PR TITLE
added details manager ui and blog detail view

### PR DESCRIPTION
**Pull request by mtrevin93**
Code changed: Added Blog Detail Manager IUserInterface and option to navigate to it from blog menu

To test:
1) Fetch branch
2) Navigate to mat-blog-details branch
3) Run app, navigate to blog management
4)  Select blog details
5)  Choose a blog from list
6) View details to see blog title & URL

### CODE REVIEW

**Comment by sxiong0519** [comment]
💯

**Comment by sxiong0519** [comment]
💯

**Comment by mtrevin93** [comment]
Fixed bug with detail view. 
Also checkout out 
Author Management => Author Details
And
Author Details => Add Tag to Author

**Comment by sxiong0519** [comment]
💯

**Comment by hcrudge** [comment]
🥇 Looks great!

**Pull request merged**
